global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"] # is scraping itself
  - job_name: "otel-collector"
    static_configs:
    - targets: ["otel-collector:9292"] # scraping the Prometheus exporter in the Opentelemtry collector
