server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: app
  static_configs:
  - targets:
      - localhost
    labels:
        job: echosvc
        __path__: /var/log/echo.log
  pipeline_stages:
    - json:
        expressions:
          level: level
          payload: msg
          timestamp: time
          service: service
    - labels:
        level:
        service:

